# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('author', models.CharField(max_length=16, verbose_name='Author')),
                ('content', models.TextField(verbose_name='Content')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.CharField(max_length=140, verbose_name='Content')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='CreateTime')),
                ('aticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Aticle', verbose_name='Artile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='aticle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='aticle',
            name='tags',
            field=models.ManyToManyField(to='Blog.Tag', verbose_name='Tag'),
        ),
    ]
