# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aticle',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='aticle',
            new_name='article',
        ),
    ]
