# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_friendlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='Blog.Tag', verbose_name='Tag'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
