# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20161019_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='Blog.Category', verbose_name='Category'),
        ),
    ]
