# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20161103_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='permalink',
            field=models.SlugField(null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Category', verbose_name='Category'),
        ),
    ]
