# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20161103_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='permalink',
            field=models.SlugField(null=True, verbose_name='Link'),
        ),
    ]
