# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20161104_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createTime',
            field=models.DateTimeField(verbose_name='CreateTime'),
        ),
    ]
